Exercice 4 MVC/Models/ErrorViewModel.cs
namespace Exercice_4_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Exercice 4 MVC/Models/VerifyCode.cs
namespace Exercice_4_MVC.Models
{
    public class VerifyCode
    {
        public int Id { get; set; }
        public string Code { get; set; } = string.Empty;
    }
}

Exercice 4 MVC/Models/Warehouse.cs
namespace Exercice_4_MVC.Models
{
    public class Warehouse
    {
        public int Id { get; set; }

        public string Name { get; set; } = string.Empty;

        public string Address { get; set; } = string.Empty;

        public int PostalCode { get; set; }


        /// <summary>
        /// Cette liste contient les codes accès du warehouse en md5.
        /// </summary>
        public List<string> CodeAccesMD5 { get; set; } = new();
    }
}

Exercice 4 MVC/Controllers/HomeController.cs
using Exercice_4_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Exercice_4_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Exercice 4 MVC/Controllers/WarehouseController.cs
using Exercice_4_MVC.Models;
using Exercice_4_MVC.Service;
using Microsoft.AspNetCore.Mvc;

namespace Exercice_4_MVC.Controllers
{
    public class WarehouseController : Controller
    {
        private readonly WarehouseService warehouseService;

        public WarehouseController()
        {
            warehouseService = new WarehouseService();
        }

        // GET: WarehouseController
        public ActionResult Index()
        {
            return View(warehouseService.GetWarehouses());
        }

        // GET: WarehouseController/Details/5
        public ActionResult Details(int id)
        {
            // Search throught warehouses list the target warehouse by id
            var foundWarehouse = warehouseService.GetWarehouses().FirstOrDefault(w => w.Id == id);

            return View(foundWarehouse);
        }

        // GET: WarehouseController/Create
        public ActionResult Create()
        {
            return View(new Warehouse());
        }

        // POST: WarehouseController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                //int newId = WarehouseController.Warehouses.Select(w => w.Id).Aggregate((previusMax, current) => { return Math.Max(previusMax, current); }) + 1;
                Warehouse warehouse = new Warehouse();
                ApplyFormCollectionToWarehouse(collection, warehouse);
                warehouseService.Add(warehouse);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: WarehouseController/Edit/5
        public ActionResult Edit(int id)
        {
            // Search throught warehouses list the target warehouse by id
            var foundWarehouse = warehouseService.GetWarehouses().FirstOrDefault(w => w.Id == id);
            if (foundWarehouse == null)
            {
                return NotFound();
            }

            return View(foundWarehouse);
        }

        // POST: WarehouseController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // Search throught warehouses list the target warehouse by id
                var foundWarehouse = warehouseService.GetWarehouses().FirstOrDefault(w => w.Id == id);
                if (foundWarehouse is null)
                {
                    throw new Exception();
                }
                ApplyFormCollectionToWarehouse(collection, foundWarehouse);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        
        public IActionResult GenerateCode(int id)
        {
            var code = warehouseService.GenerateCode(id);
            TempData["Edit"] = code;
            return RedirectToAction(nameof(Edit), nameof(Warehouse), new { id });
        }

        public IActionResult ViewCode()
        {
            ViewBag.IsVeryfied = false;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ViewCode(int id, string code)
        {
            var foundWarehouse = warehouseService.GetWarehouses().FirstOrDefault(w => w.Id == id);
            if (foundWarehouse == null)
            {
                throw new Exception("L'entrepôt n'existe pas");
            }
            ViewBag.IsVeryfied = warehouseService.VerifyCode(id, code);
            return View();
        }

        private void ApplyFormCollectionToWarehouse(IFormCollection collection, Warehouse foundWarehouse)
        {
            foreach (var field in collection)
            {
                if (field.Key == nameof(foundWarehouse.Id))
                {
                    foundWarehouse.Id = int.Parse(field.Value);
                }
                else if (field.Key == nameof(foundWarehouse.Name))
                {
                    foundWarehouse.Name = field.Value;
                }
                else if (field.Key == nameof(foundWarehouse.Address))
                {
                    foundWarehouse.Address = field.Value;
                }
                else if (field.Key == nameof(foundWarehouse.PostalCode))
                {
                    foundWarehouse.PostalCode = int.Parse(field.Value);
                }
            }
        }

        // GET: WarehouseController/Delete/5
        public ActionResult Delete(int id)
        {
            // Search throught warehouses list the target warehouse by id
            var foundWarehouse = warehouseService.GetWarehouses().FirstOrDefault(w => w.Id == id);

            return View(foundWarehouse);
        }

        // POST: WarehouseController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // Search throught warehouses list the target warehouse by id
                var foundWarehouse = warehouseService.GetWarehouses().FirstOrDefault(w => w.Id == id);
                if(foundWarehouse != null)
                {
                    warehouseService.Remove(foundWarehouse);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Exercice 4 MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Exercice 4 MVC/Views/Shared/_GenerateCode.cshtml
<a asp-controller="Warehouse" asp-action="GenerateCode" asp-route-id="@Model.Id" class="btn btn-primary">Générer un code</a>

Exercice 4 MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Exercice_4_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Exercice_4_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Exercice_4_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Menu items navbar-->
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Warehouse" asp-action="Index">Warehouse</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Warehouse" asp-action="ViewCode">Verify code</a>
                        </li>
                        <!-- Add below this line new menu item-->

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Exercice_4_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Exercice 4 MVC/Views/Shared/_WarehouseForm.cshtml
@{
    string action;
    if (ViewData["Title"]?.ToString() == "Create")
        action = "Create";
    else
        action = "Save";
    
    var Id = Model.Id;
    var Name = Model.Name;
    var Address = Model.Address;
    var PostalCode = Model.PostalCode;
}

<form asp-action="@ViewData["Title"]">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="@Id" class="control-label"></label>
        <input asp-for="@Id" class="form-control" />
        <span asp-validation-for="@Id" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Name" class="control-label"></label>
        <input asp-for="@Name" class="form-control" />
        <span asp-validation-for="@Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Address" class="control-label"></label>
        <input asp-for="@Address" class="form-control" />
        <span asp-validation-for="@Address" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@PostalCode" class="control-label"></label>
        <input asp-for="@PostalCode" class="form-control" />
        <span asp-validation-for="@PostalCode" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="@action" class="btn btn-primary" />
    </div>
</form>

Exercice 4 MVC/Views/Warehouse/Create.cshtml
@model Exercice_4_MVC.Models.Warehouse

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Warehouse</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @{
            await Html.RenderPartialAsync("_WarehouseForm", Model);
        }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Exercice 4 MVC/Views/Warehouse/Delete.cshtml
@model Exercice_4_MVC.Models.Warehouse

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Warehouse</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Exercice 4 MVC/Views/Warehouse/Details.cshtml
@model Exercice_4_MVC.Models.Warehouse

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Warehouse</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Exercice 4 MVC/Views/Warehouse/Edit.cshtml
@model Exercice_4_MVC.Models.Warehouse

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Warehouse</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @{
            await Html.RenderPartialAsync("_WarehouseForm", Model);
            await Html.RenderPartialAsync("_GenerateCode", Model);
        }
    </div>
    <label>@TempData["Edit"]</label>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Exercice 4 MVC/Views/Warehouse/Index.cshtml
@model IEnumerable<Exercice_4_MVC.Models.Warehouse>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostalCode)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostalCode)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new { item.Id }) |
                    @Html.ActionLink("Details", "Details", new { item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

Exercice 4 MVC/Views/Warehouse/Liste.cshtml
@model IEnumerable<Exercice_4_MVC.Models.Warehouse>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostalCode)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostalCode)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

Exercice 4 MVC/Views/Warehouse/ViewCode.cshtml
@model Exercice_4_MVC.Models.VerifyCode

@{
    string message;
    if (ViewBag.IsVeryfied)
        message = "Le code est validé";
    else
        message = "Le code n'est pas validé";

    ViewData["ViewCode"] = "ViewCode";
}

<form asp-action="@ViewData["ViewCode"]">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Id" class="control-label"></label>
        <input asp-for="Id" class="form-control" />
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Code" class="control-label"></label>
        <input asp-for="Code" class="form-control" />
        <span asp-validation-for="Code" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Verify" class="btn btn-primary" />
    </div>
</form>

<label>@message</label>

<div>
    <a asp-action="Index">Back to List</a>
</div>